import { MagazineProject, MagazineTheme } from "../types/magazine";

export const MAGAZINE_THEMES: MagazineTheme[] = [
  {
    id: "montanha-titanium",
    name: "Montanha Mad Methods (Industrial Yellow)",
    description: "Estética My Mad Methods: Preto profundo, cinza industrial, amarelo de alta visibilidade e tipografia tática ultra-pesada.",
    primaryColor: "#FACC15", // Industrial Yellow
    accentColor: "#EAB308",
    textColor: "#0F172A",
    bgLight: "#F8FAFC",
    bgDark: "#0B0F19",
    cardBg: "#111827",
    borderColor: "#374151",
    fontHeadline: "font-sans font-black tracking-tighter uppercase",
    fontBody: "font-sans leading-relaxed text-slate-800",
    fontSerif: false,
  },
  {
    id: "tactical-iron",
    name: "Tactical Iron & Orange",
    description: "Laranja de sinalização agressivo, grafite fosco e detalhes em stencil técnico de treinamento não-convencional.",
    primaryColor: "#F97316", // Warning Orange
    accentColor: "#EA580C",
    textColor: "#0F172A",
    bgLight: "#FFF7ED",
    bgDark: "#090D16",
    cardBg: "#1E293B",
    borderColor: "#475569",
    fontHeadline: "font-mono font-black tracking-tight uppercase",
    fontBody: "font-sans leading-relaxed text-slate-800",
    fontSerif: false,
  },
  {
    id: "monochrome-grit",
    name: "Monochrome Heavy Iron & Red",
    description: "Alto contraste bruto em preto e branco marfim, textura de ferro fundido e destaques em vermelho rubi.",
    primaryColor: "#EF4444", // Crimson Red
    accentColor: "#FFFFFF",
    textColor: "#18181B",
    bgLight: "#F4F4F5",
    bgDark: "#000000",
    cardBg: "#18181B",
    borderColor: "#27272A",
    fontHeadline: "font-sans font-black tracking-tight uppercase",
    fontBody: "font-sans leading-relaxed text-zinc-900",
    fontSerif: false,
  },
  {
    id: "cyber-neon",
    name: "Cyber Tech & Conditioning",
    description: "Estética futurista e biohacking com destaques em ciano elétrico e visual geométrico afiado.",
    primaryColor: "#06B6D4",
    accentColor: "#3B82F6",
    textColor: "#0F172A",
    bgLight: "#F0FDF4",
    bgDark: "#020617",
    cardBg: "#0F172A",
    borderColor: "#1E293B",
    fontHeadline: "font-mono font-extrabold tracking-tighter uppercase",
    fontBody: "font-sans leading-relaxed text-slate-700",
    fontSerif: false,
  },
  {
    id: "vogue-haute",
    name: "Editorial Classic & Luxury",
    description: "Elegância pura em preto e branco marfim com tipografia serifada clássica.",
    primaryColor: "#111827",
    accentColor: "#6B7280",
    textColor: "#1F2937",
    bgLight: "#FAFAF9",
    bgDark: "#18181B",
    cardBg: "#F4F4F5",
    borderColor: "#E4E4E7",
    fontHeadline: "font-serif font-bold tracking-normal",
    fontBody: "font-serif leading-loose text-stone-800",
    fontSerif: true,
  },
  {
    id: "wellness-botanic",
    name: "Wellness & Natureza",
    description: "Tons terrosos e verde esmeralda com estilo orgânico para saúde e longevidade.",
    primaryColor: "#059669",
    accentColor: "#10B981",
    textColor: "#064E3B",
    bgLight: "#F0FDF4",
    bgDark: "#064E3B",
    cardBg: "#ECFDF5",
    borderColor: "#A7F3D0",
    fontHeadline: "font-sans font-semibold tracking-wide uppercase",
    fontBody: "font-sans leading-relaxed text-emerald-950",
    fontSerif: false,
  },
];

export const INITIAL_MAGAZINE_PROJECT: MagazineProject = {
  id: "montanha-mag-01",
  title: "MONTANHA MAGAZINE",
  subtitle: "UNCONVENTIONAL STRENGTH & PERFORMANCE",
  editionNumber: "01",
  volume: "VOL. 01",
  date: "SETEMBRO 2026",
  category: "UNCONVENTIONAL TRAINING",
  themeId: "montanha-titanium",
  coverConfig: {
    mastheadText: "MONTANHA MAGAZINE",
    sloganText: "UNCONVENTIONAL STRENGTH & PERFORMANCE",
    issueBadge: "ISSUE #01 • SPECIAL COLLECTOR DOSSIER",
    mainHeadline: "UNCONVENTIONAL STRENGTH: THE HEAVY IRON REVOLUTION",
    subHeadline: "DOMINANDO KETTLEBELLS, MACES, SANDBAGS E PROTOCOLOS DE FORÇA BRUTA PARA UMA PERFORMANCE INDESTRUTÍVEL.",
    authorCallout: "POR COACH MONTANHA & MASTER ATHLETES",
    categoryTag: "EXCLUSIVE DOSSIER",
    issueDate: "SETEMBRO 2026",
    editionNumber: "Nº 01",
    priceBadge: "TECHNICAL SPEC / ED. 01",
    barcodeText: "9 771234 567003 01",
    hexBadgeText: "VOL.01 // DOC.01",
    coverStyleVariant: "mad-methods",
    showHazardStripe: true,
    showTechHud: true,
    backgroundImage: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1600&q=85",
    backgroundOverlayOpacity: 45,
    highlights: [
      {
        id: "hl-1",
        tag: "// 01. BALÍSTICA & POTÊNCIA",
        title: "Kettlebell Swing Pesado: O Segredo para Cadeia Posterior e Condicionamento de Choque",
        authorCallout: "Coach Montanha",
        pageTarget: 5,
      },
      {
        id: "hl-2",
        tag: "// 02. PROTOCOLO DE FORÇA",
        title: "Double KB Strength Protocol: O Plano de Ataque em Clusters A1/A2 e B1/B2",
        authorCallout: "Coach Montanha",
        pageTarget: 6,
      },
      {
        id: "hl-3",
        tag: "// 03. GEAR & PROMOTION",
        title: "Montanha Pro Kettlebells: Fundição Maciça de Precisão",
        authorCallout: "Montanha Gear",
        pageTarget: 7,
      },
      {
        id: "hl-4",
        tag: "// 04. FACILITY SPOTLIGHT",
        title: "Montanha Performance Lab: O Templo do Treinamento Não-Convencional",
        authorCallout: "Staff Montanha",
        pageTarget: 8,
      },
    ],
    footerHighlights: [
      "KETTLEBELL DYNAMICS",
      "STEEL MACEBELLS",
      "SANDBAGS",
      "HEAVY IRON",
      "RAW CONDITIONING",
    ],
  },
  editorialInfo: {
    editorName: "Coach Montanha",
    editorRole: "Fundador & Editor-Chefe",
    editorPhoto: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=600&q=80",
    editorActionPhoto: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=85",
    editorLetterTitle: "O MANIFESTO DA FORÇA NÃO-CONVENCIONAL",
    editorLetter: `Bem-vindo à edição inaugural da MONTANHA MAGAZINE.

Esta publicação é uma declaração de guerra contra o treino passivo, as máquinas guiadas que anestesiam o corpo e as ilusões de atalhos confortáveis. Inspirada pela metodologia crua e visceral do treinamento não-convencional (My Mad Methods style), nossa missão é resgatar a capacidade física primordial do ser humano.

Aqui, o ferro fundido, os kettlebells pesados, as clavas de aço, os sacos de areia e o próprio peso corporal são ferramentas de transformação profunda. Não buscamos apenas hipertrofia estética; forjamos poder explosivo, estabilidade angular, mobilidade blindada e uma mente que não se curva sob pressão.

Abrace a fricção. Domine a técnica nos detalhes invisíveis. Seja bem-vindo à irmandade da alta performance.`,
    editorialNote: "Montanha Magazine é um periódico dedicado a métodos não-convencionais de força, calistenia pesada, condicionamento tático e mindset espartano.",
    disclaimerText: "AVISO LEGAL & MÉDICO: Os métodos de treinamento, exercícios não-convencionais e protocolos descritos nesta publicação exigem disciplina e supervisão técnica. Consulte sempre um médico e um profissional de educação física antes de iniciar qualquer programa de alta intensidade. Todos os direitos reservados à Montanha Media Group © 2026.",
    credits: [
      { id: "c1", role: "Editor-Chefe & Direção Geral", name: "Coach Montanha" },
      { id: "c2", role: "Direção de Arte & Design Tático", name: "Montanha Tactical Design" },
      { id: "c3", role: "Pesquisa & Fisiologia Não-Convencional", name: "Conselho de Força & Biomecânica" },
      { id: "c4", role: "Fotografia Editorial de Ação", name: "Montanha Iron Media" },
    ],
    contributors: [
      {
        id: "con-1",
        name: "COACH MONTANHA",
        title: "MASTER KETTLEBELL INSTRUCTOR // FOUNDER",
        bio: "Pioneiro do treinamento não-convencional e biomecânica de alta performance no Brasil. Especialista em força balística e periodização tática.",
        photo: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=400&q=80",
        handle: "@coachmontanha",
        facility: "MONTANHA IRON LAB // MATRIZ",
      },
      {
        id: "con-2",
        name: "DRA. HELENA VASCONCELOS",
        title: "NEUROCIENTISTA & BIOHACKER // MD",
        bio: "Pesquisadora em fisiologia do sono profundo, variabilidade cardíaca (HRV) e restauração neuromuscular em atletas de alto rendimento.",
        photo: "https://images.unsplash.com/photo-1594824813628-98e3b48a1c97?auto=format&fit=crop&w=400&q=80",
        handle: "@drahelenavasconcelos",
        facility: "NEURORECOVERY INSTITUTE",
      },
      {
        id: "con-3",
        name: "MARCUS 'VIKING' SILVA",
        title: "STEEL MACE & CLUBBELL SPECIALIST // CSCS",
        bio: "Instrutor sênior de alavancas rotacionais e treinamento tridimensional. Focado em saúde escapular e prevenção de lesões em esportes de combate.",
        photo: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=400&q=80",
        handle: "@viking.strength",
        facility: "TACTICAL COMBAT LAB",
      },
    ],
  },
  articles: [
    {
      id: "art-1",
      title: "KETTLEBELL DYNAMICS: O PODER BALÍSTICO DO SWING",
      subtitle: "Como o kettlebell pesado recruta a cadeia posterior, desenvolve potência de quadril e cria um motor cardiovascular inesgotável.",
      category: "MONTANHA METHOD",
      author: "Coach Montanha",
      authorBio: "Master Kettlebell Instructor e Fundador.",
      authorPhoto: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=300&q=80",
      heroImage: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1400&q=85",
      heroImageCaption: "A aceleração violenta do quadril combinada ao travamento dorsal engaja mais de 600 músculos por segundo.",
      heroImagePrompt: "Athletic fighter doing heavy kettlebell swing in dark gritty industrial gym, chalk dust, cinematic rim lighting, 8k",
      content: `O kettlebell não é apenas um haltere com alça; é uma ferramenta de aceleração centrífuga e desaceleração excêntrica violenta. Ao contrário dos pesos convencionais onde a trajetória é linear e estática, o kettlebell exige que o sistema neuromuscular estabilize forças dinâmicas em múltiplos planos.

**A Explosão do Hinge de Quadril**
O exercício mestre — o Kettlebell Swing Hardstyle — ensina o corpo a gerar potência máxima a partir dos glúteos e isquiotibiais, transferindo essa força através de um core travado em prancha balística. Em milissegundos, o atleta transita do relaxamento elástico para uma contração isométrica total.

**Densidade e Capacidade de Trabalho**
Ao combinar protocolos de 10x10 com kettlebells de 32kg ou 40kg, o limiar de lactato é empurrado a níveis extremos. O coração opera na zona anaeróbica enquanto as fibras musculares do tipo II são recrutadas em sua plenitude.`,
      pullQuotes: [
        "O kettlebell pune a negligência e premia o respeito: domine a trajetória ou seja dominado por ela.",
      ],
      calloutBox: {
        title: "REGRA DE OURO DO COACH",
        content: "A força gerada no swing vem 100% da flexão e extensão explosiva do quadril. Os braços atuam apenas como cordas que conectam o peso ao seu tronco.",
      },
      keyTakeaways: [
        "A força vem do quadril, nunca dos braços.",
        "Mantenha a coluna neutra e a dorsal engatada para proteger a lombar.",
        "Expire com força no topo do movimento criando pressão intra-abdominal máxima.",
      ],
      layoutTemplate: "editorial-lead",
      tags: ["Kettlebell", "Balística", "Cadeia Posterior", "Montanha"],
      estimatedReadTime: 5,
      featuredOnCover: true,
    },
    {
      id: "art-2",
      title: "DOUBLE KB STRENGTH PROTOCOL: DENSIDADE MÁXIMA",
      subtitle: "Estrutura avançada de treinamento dividida em clusters A1/A2 e B1/B2 com controle de tempo e descanso ativo.",
      category: "MONTANHA WORKOUT",
      author: "Coach Montanha",
      authorBio: "Master Kettlebell Instructor // CSCS",
      authorPhoto: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=300&q=80",
      heroImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1400&q=85",
      heroImageCaption: "O rack duplo exige estabilização torácica massiva sob carga de ferro fundido.",
      content: `Este protocolo foi desenvolvido para atletas que buscam desenvolver força bruta, capacidade de trabalho e densidade muscular sem perder agilidade atlética.

**Como Executar o Treino:**
Execute os blocos em super-séries alternadas (A1 seguido de A2). Respeite os 90 segundos de descanso antes de iniciar a próxima série. Foque na perfeição biomecânica de cada repetição.`,
      pullQuotes: [
        "A disciplina na contagem do tempo sob tensão separa o praticante amador do atleta de elite.",
      ],
      layoutTemplate: "workout-protocol",
      workoutProtocol: {
        workoutTitle: "DOUBLE KB STRENGTH PROTOCOL // DOSSIER #01",
        warmupPrep: "MOBILITY & ACTIVATION (5 MIN): Thoracic spine bridges, Halos com kettlebell leve (3x10 cada lado), Prying Goblet Squats e Pranchas com ativação glútea.",
        exercises: [
          {
            code: "A1",
            name: "DOUBLE KETTLEBELL CLEAN & STRICT PRESS",
            setsReps: "5 SÉRIES × 5 REPETIÇÕES",
            tempoRest: "TEMPO: 20X1 // DESCANSO: 90s",
            keyPoints: "Trave os glúteos e abdômen no rack, empurre o chão com os pés e pressione em linha vertical pura.",
          },
          {
            code: "A2",
            name: "HEAVY DOUBLE KETTLEBELL FRONT SQUATS",
            setsReps: "5 SÉRIES × 5 REPETIÇÕES",
            tempoRest: "TEMPO: 31X1 // DESCANSO: 90s",
            keyPoints: "Cotovelos altos no rack, quebre o quadril abaixo do paralelo e suba explodindo sem perder a postura torácica.",
          },
          {
            code: "B1",
            name: "ALTERNATING GORILLA ROWS",
            setsReps: "4 SÉRIES × 8 REPETIÇÕES (CADA LADO)",
            tempoRest: "TEMPO: 2011 // DESCANSO: 60s",
            keyPoints: "Tronco paralelo ao solo, puxe com o cotovelo rente à costela e pressione o outro peso contra o chão.",
          },
          {
            code: "B2",
            name: "RENEGADE ROWS & STRICT PUSHUPS",
            setsReps: "4 SÉRIES × 6 REPETIÇÕES",
            tempoRest: "TEMPO: 20X0 // DESCANSO: 60s",
            keyPoints: "Pés afastados na largura dos ombros para evitar rotação de quadril. Core 100% estático.",
          },
          {
            code: "FINISHER",
            name: "HEAVY FARMER CARRY PROTOCOL",
            setsReps: "4 TIROS × 40 METROS (CARGA MÁXIMA 32KG+)",
            tempoRest: "TEMPO: CONSTANTE // DESCANSO: 60s",
            keyPoints: "Postura ereta, ombros encaixados para trás e para baixo. Passos curtos e respiração ritmada.",
          },
        ],
        finisher: "FINISHER: Heavy Sandbag Carry (3x50m) ou 100 Snatsches com 24kg em esforço contínuo.",
        videoQrUrl: "https://coachmontanha.com.br/protocolo-01",
      },
      tags: ["Workout", "Protocolo", "Kettlebell", "Força"],
      estimatedReadTime: 6,
      featuredOnCover: true,
    },
    {
      id: "art-3",
      title: "MONTANHA COMPETITION KETTLEBELLS // PRO SERIES",
      subtitle: "Fundição de peça única em ferro dúctil, empunhadura texturizada a pó e calibração de precisão milimétrica.",
      category: "GEAR & PROMOTION",
      author: "Montanha Equipment",
      authorBio: "Engenharia de Equipamentos Pesados",
      heroImage: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1400&q=85",
      heroImageCaption: "Desenvolvido para resistir a décadas de impacto brutal em solo de concreto.",
      content: `A precisão no treinamento começa com o peso correto. A linha Montanha Competition foi forjada para oferecer pegada antiderrapante sem agredir a pele das mãos e equilíbrio perfeito de massa.`,
      pullQuotes: ["Ferro de verdade para atletas sem desculpas."],
      layoutTemplate: "product-ad",
      productPromotion: {
        slogan: "FORGED IN IRON // BUILT FOR WAR",
        productName: "MONTANHA COMPETITION KETTLEBELLS",
        productSubtitle: "Fundição de peça única em ferro dúctil com acabamento antiderrapante a pó e calibração de precisão (+/- 0.5%).",
        productImage: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1400&q=85",
        promoBadgeText: "SPECIAL LAUNCH OFFER // 15% OFF",
        couponCode: "MONTANHA15",
        ctaUrl: "WWW.MONTANHAIRON.COM.BR",
        specBadges: [
          { title: "GRAVITY CAST", subtitle: "Single pour ductile iron" },
          { title: "POWDER COAT", subtitle: "Matte textured grip" },
          { title: "CALIBRATED", subtitle: "+/- 0.5% precision weight" },
          { title: "LIFETIME SPEC", subtitle: "Indestructible warranty" },
        ],
        features: [
          "Fundição em bloco único sem soldas",
          "Diâmetro de alça de 35mm para pegada de competição",
          "Código de cores internacional padrão IUKL",
        ],
      },
      tags: ["Gear", "Kettlebell", "Promo", "Iron"],
      estimatedReadTime: 2,
      featuredOnCover: false,
    },
    {
      id: "art-4",
      title: "MONTANHA PERFORMANCE & IRON LAB // SP",
      subtitle: "Conheça o centro de excelência em treinamento não-convencional, biomecânica e avaliação metabólica.",
      category: "STUDIO SPOTLIGHT",
      author: "Equipe Editorial",
      authorBio: "Dossiê de Espaços e Instalações",
      heroImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1400&q=85",
      content: `Projetado como um santuário para o treinamento de força pura, o Montanha Lab elimina o supérfluo para focar no que realmente constrói atletas resilientes: ferro maciço, alavancas assimétricas e protocolos de intensidade implacável.`,
      pullQuotes: ["O ambiente certo não apenas inspira o esforço; ele torna a mediocridade insuportável."],
      layoutTemplate: "facility-spotlight",
      facilitySpotlight: {
        facilityName: "MONTANHA PERFORMANCE & IRON LAB",
        headCoach: "COACH MONTANHA",
        location: "SÃO PAULO // SP - BRASIL",
        website: "WWW.MONTANHALAB.COM.BR",
        methodsUsed: ["KETTLEBELLS", "STEEL MACES", "CLUBBELLS", "CALISTHENICS", "MOBILITY LAB"],
        specialties: ["Força Não-Convencional", "Condicionamento Tático", "Prevenção de Lesões"],
        galleryPhotos: [
          "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=600&q=80",
          "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80",
          "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80",
        ],
        overviewText: "Projetado como um santuário para o treinamento de força pura, o Montanha Lab elimina o supérfluo para focar no que realmente constrói atletas resilientes: ferro maciço, alavancas assimétricas e protocolos de intensidade implacável.",
        missionText: "Nossa missão é transformar cada praticante em uma máquina de adaptação motora. Não ensinamos apenas movimentos; cultivamos a mentalidade espartana de execução sem desculpas em cada repetição.",
        philosophyText: "Sem máquinas guiadas. Sem esteiras anestésicas. Apenas você, a gravidade e o ferro.",
        anchoredQuote: "O ambiente certo não apenas inspira o esforço; ele torna a mediocridade insuportável.",
      },
      tags: ["Studio", "Spotlight", "Lab", "Academia"],
      estimatedReadTime: 3,
      featuredOnCover: false,
    },
  ],
  backCoverConfig: {
    headline: "FORJA O SEU CORPO. DOMINA A SUA MENTE.",
    subheadline: "Junte-se à fraternidade do Coach Montanha e treine com métodos não-convencionais de elite.",
    message: "A mediocridade é uma escolha, a excelência é uma disciplina diária. Pegue o peso, calce o tênis e vá para a arena.",
    backgroundImage: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1600&q=85",
    ctaText: "ACESSE O PROTOCOLO UNCONVENTIONAL",
    websiteUrl: "www.coachmontanha.com.br",
    socialHandles: {
      instagram: "@coachmontanha",
      youtube: "Coach Montanha Oficial",
      email: "contato@coachmontanha.com.br",
    },
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
