import { MagazineProject, MagazineTheme } from "../types/magazine";

export const MAGAZINE_THEMES: MagazineTheme[] = [
  {
    id: "montanha-titanium",
    name: "Montanha Titanium (Padrão Industrial)",
    description: "Estética My Mad Methods: Preto profundo, amarelo industrial (#FACC15) e cinza titânio.",
    category: "dark",
    primaryColor: "#FACC15",
    accentColor: "#F59E0B",
    textColor: "#FFFFFF",
    bgLight: "#FFFFFF",
    bgDark: "#0B0F19",
    cardBg: "#111827",
    borderColor: "#FACC15",
    fontHeadline: "font-sans",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "tactical-iron",
    name: "Tactical Iron & Warning Orange",
    description: "Laranja tático militar (#FB923C) de alta visibilidade sobre metal escovado e aço fundido.",
    category: "dark",
    primaryColor: "#FB923C",
    accentColor: "#F97316",
    textColor: "#FFFFFF",
    bgLight: "#F8FAFC",
    bgDark: "#090D16",
    cardBg: "#131B2E",
    borderColor: "#FB923C",
    fontHeadline: "font-mono",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "monochrome-grit",
    name: "Monochrome Heavy Grit & Red",
    description: "Preto e branco marfim com alto contraste e acentos em vermelho rubi de combate (#EF4444).",
    category: "dark",
    primaryColor: "#EF4444",
    accentColor: "#DC2626",
    textColor: "#FFFFFF",
    bgLight: "#F4F4F5",
    bgDark: "#050505",
    cardBg: "#121212",
    borderColor: "#EF4444",
    fontHeadline: "font-sans",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "vogue-haute",
    name: "Vogue Haute Editorial (Fundo Branco)",
    description: "Design clássico com fundo 100% branco editorial (#FAFAF9), tipografia preta elegante e serifas.",
    category: "light",
    primaryColor: "#0F172A",
    accentColor: "#475569",
    textColor: "#0F172A",
    bgLight: "#FAFAF9",
    bgDark: "#FAFAF9",
    cardBg: "#FFFFFF",
    borderColor: "#CBD5E1",
    fontHeadline: "font-serif",
    fontBody: "font-serif",
    fontSerif: true,
    isLight: true,
  },
  {
    id: "cyber-neon",
    name: "Cyber Performance & Electric Blue",
    description: "Visual futurista de biohacking com azul elétrico (#38BDF8) e grid de alta tecnologia.",
    category: "vibrant",
    primaryColor: "#38BDF8",
    accentColor: "#0284C7",
    textColor: "#FFFFFF",
    bgLight: "#F0F9FF",
    bgDark: "#030712",
    cardBg: "#0F172A",
    borderColor: "#38BDF8",
    fontHeadline: "font-mono",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "wellness-botanic",
    name: "Warrior Botanic & Deep Emerald",
    description: "Verde esmeralda profundo (#34D399) para matérias de nutrição, longevidade e força natural.",
    category: "dark",
    primaryColor: "#34D399",
    accentColor: "#059669",
    textColor: "#FFFFFF",
    bgLight: "#F0FDF4",
    bgDark: "#061A14",
    cardBg: "#0B2E24",
    borderColor: "#34D399",
    fontHeadline: "font-sans",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "olimpo-gold",
    name: "Olimpo Gold & Obsidian Luxury",
    description: "Ouro real nobre (#EAB308) sobre fundo preto ônix com detalhes em bronze e sofisticação de elite.",
    category: "dark",
    primaryColor: "#EAB308",
    accentColor: "#CA8A04",
    textColor: "#FFFFFF",
    bgLight: "#FEFCE8",
    bgDark: "#050508",
    cardBg: "#14110B",
    borderColor: "#EAB308",
    fontHeadline: "font-serif",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "desert-coyote",
    name: "Desert Storm & Coyote Camo",
    description: "Areia militar tática (#D4A373) e bege deserto sobre marrom chumbo, focado em expedições outdoor.",
    category: "dark",
    primaryColor: "#D4A373",
    accentColor: "#E9D8A6",
    textColor: "#FFFFFF",
    bgLight: "#FEF3C7",
    bgDark: "#13100D",
    cardBg: "#221C16",
    borderColor: "#D4A373",
    fontHeadline: "font-mono",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "nordic-ice",
    name: "Nordic Minimalist & Polar Ice (Fundo Claro)",
    description: "Fundo branco polar suave (#F8FAFC), azul glacial (#0284C7) e tipografia escandinava ultra limpa.",
    category: "light",
    primaryColor: "#0284C7",
    accentColor: "#0369A1",
    textColor: "#0F172A",
    bgLight: "#F8FAFC",
    bgDark: "#F8FAFC",
    cardBg: "#FFFFFF",
    borderColor: "#BAE6FD",
    fontHeadline: "font-sans",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: true,
  },
  {
    id: "gladiator-crimson",
    name: "Gladiator Crimson & Blood Iron",
    description: "Vinho imperial e vermelho forja (#DC2626) sobre preto grafite com detalhes de combate corpo a corpo.",
    category: "dark",
    primaryColor: "#DC2626",
    accentColor: "#991B1B",
    textColor: "#FFFFFF",
    bgLight: "#FEF2F2",
    bgDark: "#0D0506",
    cardBg: "#1F0C0F",
    borderColor: "#DC2626",
    fontHeadline: "font-sans",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "vintage-golden-era",
    name: "Golden Era 1970 & Vintage Iron",
    description: "Amarelo mostarda retrô (#E6AF2E), marrom couro envelhecido e visual clássico dos anos de ouro da musculação.",
    category: "dark",
    primaryColor: "#E6AF2E",
    accentColor: "#C98A16",
    textColor: "#FFFFFF",
    bgLight: "#FFFBEB",
    bgDark: "#140F0A",
    cardBg: "#261D15",
    borderColor: "#E6AF2E",
    fontHeadline: "font-serif",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "midnight-ultraviolet",
    name: "Midnight Ultraviolet & Deep Purple",
    description: "Roxo cósmico elétrico (#C084FC) e magenta neon sobre preto profundo, estética noturna de ponta.",
    category: "vibrant",
    primaryColor: "#C084FC",
    accentColor: "#A855F7",
    textColor: "#FFFFFF",
    bgLight: "#FAF5FF",
    bgDark: "#080410",
    cardBg: "#170C2E",
    borderColor: "#C084FC",
    fontHeadline: "font-sans",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "ronin-crimson",
    name: "Japanese Ronin & Sumi Ink",
    description: "Vermelho carmim imperial (#E11D48) e tinta sumi-ê sobre preto carvão com disciplina e minimalismo oriental.",
    category: "dark",
    primaryColor: "#E11D48",
    accentColor: "#BE123C",
    textColor: "#FFFFFF",
    bgLight: "#FFF1F2",
    bgDark: "#0A0A0C",
    cardBg: "#17171C",
    borderColor: "#E11D48",
    fontHeadline: "font-serif",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "concrete-monolith",
    name: "Monolith Concrete & Heavy Slate",
    description: "Cinza concreto industrial (#94A3B8) e chumbo militar sem distrações, pura força e austeridade.",
    category: "dark",
    primaryColor: "#94A3B8",
    accentColor: "#64748B",
    textColor: "#FFFFFF",
    bgLight: "#F1F5F9",
    bgDark: "#0B0F15",
    cardBg: "#151C28",
    borderColor: "#94A3B8",
    fontHeadline: "font-mono",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "acid-lime-athletic",
    name: "High-Voltage Acid Lime / Cyber Athletic",
    description: "Verde-limão eletrizante (#A3E635 / #CCFF00) sobre preto asfalto puro, máxima visibilidade e impacto atlético.",
    category: "vibrant",
    primaryColor: "#A3E635",
    accentColor: "#84CC16",
    textColor: "#FFFFFF",
    bgLight: "#F7FEE7",
    bgDark: "#030303",
    cardBg: "#101308",
    borderColor: "#A3E635",
    fontHeadline: "font-sans",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: false,
  },
  {
    id: "swiss-helvetica",
    name: "Swiss International & Alpine Red (Fundo Branco)",
    description: "Design internacional suíço com fundo 100% branco (#FFFFFF), vermelho puro (#DC2626) e contraste absoluto.",
    category: "light",
    primaryColor: "#DC2626",
    accentColor: "#991B1B",
    textColor: "#000000",
    bgLight: "#FFFFFF",
    bgDark: "#FFFFFF",
    cardBg: "#F8FAFC",
    borderColor: "#DC2626",
    fontHeadline: "font-sans",
    fontBody: "font-sans",
    fontSerif: false,
    isLight: true,
  },
];


export const INITIAL_MAGAZINE_PROJECT: MagazineProject = {
  id: "proj-montanha-01",
  title: "MONTANHA",
  subtitle: "UNCONVENTIONAL STRENGTH & HIGH PERFORMANCE",
  editionNumber: "01",
  volume: "01",
  date: "SETEMBRO 2026",
  category: "UNCONVENTIONAL STRENGTH",
  themeId: "montanha-titanium",
  pageVisibility: {
    showCover: true,
    showEditorLetter: true,
    showContributors: false, // Desativada por padrão conforme solicitação do usuário
    showTableOfContents: true,
    showBackCover: true,
  },
  coverConfig: {
    mastheadText: "MONTANHA",
    sloganText: "UNCONVENTIONAL STRENGTH & PERFORMANCE",
    issueBadge: "EDIÇÃO ESPECIAL // Nº 01",
    mainHeadline: "O CÓDIGO DA ALTA PERFORMANCE",
    subHeadline: "Como reprogramar o metabolismo, construir força indestrutível e dominar a disciplina diária.",
    authorCallout: "COACH MONTANHA",
    categoryTag: "EXCLUSIVO",
    coverStyleVariant: "mad-methods",
    showHazardStripe: true,
    showTechHud: true,
    hexBadgeText: "VOL. 01 // ISSUE 01",
    textScale: 115,
    highlightsFontSize: "large",
    headlineFontSize: "large",
    highlights: [
      {
        id: "hl-1",
        tag: "HIPERTROFIA & CIÊNCIA",
        title: "Os 3 Pilares Ocultos do Ganho de Massa que a Maioria Ignora",
        authorCallout: "Coach Montanha",
        teaser: "O método científico definitivo para romper o platô muscular sem depender de atalhos.",
        pageTarget: 3,
      },
      {
        id: "hl-2",
        tag: "BIOHACKING",
        title: "Sono Profundo: A Janela de Recuperação Celular e Hormonal",
        authorCallout: "Dra. Helena Vasconcelos",
        teaser: "Como otimizar a restauração hormonal e a regeneração celular durante a noite.",
        pageTarget: 4,
      },
      {
        id: "hl-3",
        tag: "MINDSET",
        title: "A Psicologia do Vencedor: Blindando sua Mente contra a Procrastinação",
        authorCallout: "Coach Montanha",
        teaser: "A ciência prática para blindar a mente e manter consistência diária inegociável.",
        pageTarget: 5,
      },
    ],
    footerHighlights: [
      "NUTRIÇÃO DE PRECISÃO",
      "SUPLEMENTAÇÃO ESTRATÉGICA",
      "LONGEVIDADE ATIVA",
      "FORÇA BRUTA",
    ],
    backgroundImage:
      "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=2560&q=95",
    backgroundOverlayOpacity: 60,
    barcodeText: "9 772026 001008",
    priceBadge: "EDIÇÃO PREMIUM",
    issueDate: "SETEMBRO 2026",
    editionNumber: "01",
  },
  editorialInfo: {
    editorName: "COACH MONTANHA",
    editorRole: "FOUNDER & EDITOR-IN-CHIEF",
    editorPhoto:
      "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=400&q=80",
    editorActionPhoto:
      "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80",
    editorLetterTitle: "A BUSCA INCESSANTE PELA EXCELÊNCIA",
    editorLetter: `Bem-vindo à primeira edição oficial da Revista Montanha.

Este projeto nasceu de uma inquietação: no mar de conteúdos superficiais que inundam as redes sociais hoje em dia, sentimos a necessidade de criar um refúgio de conhecimento profundo, denso e verdadeiramente transformador.

Aqui, não acreditamos em atalhos mágicos ou promessas vazias. Acreditamos no poder do treino consistente, na biomecânica refinada, na ciência aplicada sem dogmas e, acima de tudo, na mentalidade inabalável.

Cada página que você ler nesta edição foi cuidadosamente diagramada para entregar não apenas informação, mas um chamado à ação. Que estas linhas sirvam de combustível para que você conquiste a sua melhor versão dentro e fora dos treinos.`,
    editorialNote: "A força não é um acidente genético; é uma decisão diária forjada no ferro.",
    isbn: "978-65-00-98765-4",
    issn: "2675-9829",
    publisherInfo: "MONTANHA EDITORIAL & PUBLICATONS LTDA. // CNPJ: 00.000.000/0001-00 // SÃO PAULO - BRASIL",
    catalogingData: "Dados Internacionais de Catalogação na Publicação (CIP)\nRevista Montanha : alta performance, força não-convencional e ciência aplicada / Editor-Chefe: Coach Montanha. -- Ed. 01 (Set. 2026) -- São Paulo : Montanha Editorial, 2026. Mensal. ISSN 2675-9829. ISBN 978-65-00-98765-4. 1. Educação física. 2. Musculação e Condicionamento. 3. Treinamento Físico. I. Montanha, Coach. CDD 613.71",
    legalText: "TODOS OS DIREITOS RESERVADOS. É rigorosamente proibida a reprodução total ou parcial desta obra por quaisquer meios eletrônicos, mecânicos, fotográficos ou gravação sem a prévia autorização expressa dos editores. As opiniões emitidas em artigos assinados são de inteira responsabilidade de seus respectivos autores.",
    disclaimerText:
      "AVISO LEGAL & MÉDICO: O conteúdo editorial desta publicação destina-se exclusivamente a fins informativos e educacionais. A prática de exercícios físicos intensos e alterações na dieta exigem avaliação médica prévia e orientação de profissionais de Educação Física e Nutrição registrados nos respectivos conselhos de classe. © 2026 Montanha Media.",
    credits: [
      { id: "c-1", role: "DIRETOR EDITORIAL", name: "Coach Montanha" },
      { id: "c-2", role: "DESIGN & DIAGRAMAÇÃO", name: "Montanha Studio AI" },
      { id: "c-3", role: "REVISÃO TÉCNICA", name: "Equipe de Performance" },
      { id: "c-4", role: "FOTOGRAFIA PRINCIPAL", name: "Montanha Media Lab" },
    ],
    contributors: [
      {
        id: "con-1",
        name: "COACH MONTANHA",
        title: "MASTER KETTLEBELL INSTRUCTOR // CSCS",
        bio: "Fundador do método não-convencional de força, especialista em preparação física de alta densidade e treinamento balístico.",
        photo: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=400&q=80",
        handle: "@coachmontanha",
        facility: "MONTANHA IRON LAB // MATRIZ",
      },
      {
        id: "con-2",
        name: "DRA. HELENA VASCONCELOS",
        title: "NEUROCIENTISTA & BIOHACKER // MD",
        bio: "Pesquisadora em fisiologia do sono profundo, variabilidade cardíaca (HRV) e restauração neuromuscular em atletas de alto rendimento.",
        photo: "https://images.unsplash.com/photo-1594824813628-98e3b48a1c97?auto=format&fit=crop&w=400&q=80",
        handle: "@drahelenavasconcelos",
        facility: "NEURORECOVERY INSTITUTE",
      },
      {
        id: "con-3",
        name: "MARCUS 'VIKING' SILVA",
        title: "STEEL MACE & CLUBBELL SPECIALIST // CSCS",
        bio: "Instrutor sênior de alavancas rotacionais e treinamento tridimensional. Focado em saúde escapular e prevenção de lesões em esportes de combate.",
        photo: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=400&q=80",
        handle: "@viking.strength",
        facility: "TACTICAL COMBAT LAB",
      },
    ],
    tocHeadline: "SUMÁRIO",
    tocSpotlightImage:
      "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1200&q=80",
    tocSpotlightTitle: "TREINAMENTO NÃO-CONVENCIONAL & ALAVANCAS DE FORÇA",
    tocSpotlightCategory: "LABORATÓRIO DE PERFORMANCE",
    editorLetterSpotlightImage:
      "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80",
    editorLetterSpotlightCaption:
      "A consistência nos detalhes invisíveis constrói o corpo e a mente indestrutíveis.",
  },
  articles: [
    {
      id: "art-1",
      title: "KETTLEBELL DYNAMICS: O PODER BALÍSTICO DO SWING",
      subtitle: "Como o kettlebell pesado recruta a cadeia posterior, desenvolve potência de quadril e cria um motor cardiovascular inesgotável.",
      category: "MONTANHA METHOD",
      author: "Coach Montanha",
      authorBio: "Master Kettlebell Instructor e Fundador.",
      authorPhoto: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=300&q=80",
      heroImage: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1400&q=85",
      heroImageCaption: "A aceleração violenta do quadril combinada ao travamento dorsal engaja mais de 600 músculos por segundo.",
      heroImagePrompt: "Athletic fighter doing heavy kettlebell swing in dark gritty industrial gym, chalk dust, cinematic rim lighting, 8k",
      content: `O kettlebell não é apenas um haltere com alça; é uma ferramenta de aceleração centrífuga e desaceleração excêntrica violenta. Ao contrário dos pesos convencionais onde a trajetória é linear e estática, o kettlebell exige que o sistema neuromuscular estabilize forças dinâmicas em múltiplos planos.

**A Explosão do Hinge de Quadril**
O exercício mestre — o Kettlebell Swing Hardstyle — ensina o corpo a gerar potência máxima a partir dos glúteos e isquiotibiais, transferindo essa força através de um core travado em prancha balística. Em milissegundos, o atleta transita do relaxamento elástico para uma contração isométrica total.

**Densidade e Capacidade de Trabalho**
Ao combinar protocolos de 10x10 com kettlebells de 32kg ou 40kg, o limiar de lactato é empurrado a níveis extremos. O coração opera na zona anaeróbica enquanto as fibras musculares do tipo II são recrutadas em sua plenitude.`,
      pullQuotes: [
        "O kettlebell pune a negligência e premia o respeito: domine a trajetória ou seja dominado por ela.",
      ],
      calloutBox: {
        title: "REGRA DE OURO DO COACH",
        content: "A força gerada no swing vem 100% da flexão e extensão explosiva do quadril. Os braços atuam apenas como cordas que conectam o peso ao seu tronco.",
      },
      keyTakeaways: [
        "A força vem do quadril, nunca dos braços.",
        "Mantenha a coluna neutra e a dorsal engatada para proteger a lombar.",
        "Expire com força no topo do movimento criando pressão intra-abdominal máxima.",
      ],
      layoutTemplate: "editorial-lead",
      tags: ["Kettlebell", "Balística", "Cadeia Posterior", "Montanha"],
      estimatedReadTime: 5,
      featuredOnCover: true,
      enabled: true,
    },
    {
      id: "art-2",
      title: "DOUBLE KB STRENGTH PROTOCOL: DENSIDADE MÁXIMA",
      subtitle: "Protocolo completo de força funcional com 2 kettlebells pesados para hipertrofia densa e potência pura.",
      category: "WORKOUT PROTOCOL",
      author: "Coach Montanha",
      authorBio: "Master Coach // Montanha Method",
      authorPhoto: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=300&q=80",
      heroImage: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=1400&q=85",
      content: "Protocolo de alta intensidade com ênfase em sobrecarga progressiva e tempo sob tensão.",
      pullQuotes: ["A simplicidade brutal do treino com dois kettlebells forja atletas indestrutíveis."],
      layoutTemplate: "workout-protocol",
      workoutProtocol: {
        workoutTitle: "COMPLEX MONSTER: DOUBLE KB STRENGTH",
        warmupPrep: "3 Rounds: 10 Halo com 16kg + 10 Cossack Squats + 5 Pranchas Escapulares. Foco em abertura de quadril e estabilidade glenoumeral.",
        exercises: [
          {
            code: "A1",
            name: "DOUBLE KB CLEAN & STRICT PRESS",
            setsReps: "5 SÉRIES × 5 REPS",
            tempoRest: "TEMPO: 20X1 // REST: 90s",
            keyPoints: "Trave glúteos e abdômen no ápice do press. Não hiperestenda a coluna lombar.",
          },
          {
            code: "A2",
            name: "DOUBLE KB FRONT SQUAT (RACK POSITION)",
            setsReps: "5 SÉRIES × 6 REPS",
            tempoRest: "TEMPO: 31X0 // REST: 90s",
            keyPoints: "Cotovelos apontando para o chão, pressão torácica contínua e descida controlada.",
          },
          {
            code: "B1",
            name: "HEAVY GORILLA ROW (PAIRED)",
            setsReps: "4 SÉRIES × 8 REPS / LADO",
            tempoRest: "TEMPO: 2110 // REST: 60s",
            keyPoints: "Tronco paralelo ao solo, puxe com o cotovelo rentes às costelas.",
          },
          {
            code: "FINISHER",
            name: "DOUBLE KB FARMER'S WALK SUICIDE",
            setsReps: "4 TIROS × 40 METROS",
            tempoRest: "TEMPO: CONTÍNUO // REST: 60s",
            keyPoints: "Carga pesada (2x28kg ou 2x32kg). Postura ereta, ombros encaixados para trás.",
          },
        ],
        finisher: "Execute os tiros de Farmer's Walk sem soltar o peso no meio do trajeto. Mantenha respiração nasal profunda entre as séries.",
        videoQrUrl: "https://www.youtube.com",
      },
      tags: ["Treino", "Double KB", "Hipertrofia", "Protocolo"],
      estimatedReadTime: 4,
      featuredOnCover: true,
      enabled: true,
    },
    {
      id: "art-3",
      title: "MONTANHA COMPETITION KETTLEBELLS // CAST IRON",
      subtitle: "Kettlebells fundidos em peça única de ferro dúctil com calibração precisa para treinamento de alta performance.",
      category: "GEAR & PROMO",
      author: "Montanha Equipment Lab",
      heroImage: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1400&q=85",
      content: "Desenvolvidos com base nas especificações dos maiores torneios internacionais de força.",
      pullQuotes: ["Ferro maciço, pegada imbatível e durabilidade para a vida toda."],
      layoutTemplate: "product-ad",
      productPromotion: {
        slogan: "FORJADO NO FERRO // CONSTRUÍDO PARA A GUERRA",
        productName: "MONTANHA PRO COMPETITION KETTLEBELL (16KG A 48KG)",
        productSubtitle: "Alça com acabamento em pintura eletrostática a pó e código de cores olímpico para troca rápida.",
        productImage: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1400&q=85",
        promoBadgeText: "CUPOM LEITOR // 15% OFF",
        couponCode: "MONTANHA15",
        ctaUrl: "WWW.MONTANHAIRON.COM.BR",
        specBadges: [
          { title: "PEÇA ÚNICA", subtitle: "Sem soldas ou emendas frágeis" },
          { title: "ACABAMENTO POWDER", subtitle: "Aderência superior de magnésio" },
          { title: "CALIBRAÇÃO +/-0.5%", subtitle: "Precisão absoluta de carga" },
          { title: "GARANTIA VITALÍCIA", subtitle: "Indestrutível contra quedas" },
        ],
        features: ["Disponível em 16kg, 20kg, 24kg, 28kg, 32kg, 40kg e 48kg", "Entrega expressa para todo o Brasil"],
      },
      tags: ["Equipamentos", "Kettlebell", "Promoção", "Gear"],
      estimatedReadTime: 2,
      featuredOnCover: false,
      enabled: true,
    },
    {
      id: "art-4",
      title: "MONTANHA PERFORMANCE & IRON LAB // SP",
      subtitle: "Conheça o centro de excelência em treinamento não-convencional, biomecânica e avaliação metabólica.",
      category: "STUDIO SPOTLIGHT",
      author: "Equipe Editorial",
      authorBio: "Dossiê de Espaços e Instalações",
      heroImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1400&q=85",
      content: `Projetado como um santuário para o treinamento de força pura, o Montanha Lab elimina o supérfluo para focar no que realmente constrói atletas resilientes: ferro maciço, alavancas assimétricas e protocolos de intensidade implacável.`,
      pullQuotes: ["O ambiente certo não apenas inspira o esforço; ele torna a mediocridade insuportável."],
      layoutTemplate: "facility-spotlight",
      facilitySpotlight: {
        facilityName: "MONTANHA PERFORMANCE & IRON LAB",
        headCoach: "COACH MONTANHA",
        location: "SÃO PAULO // SP - BRASIL",
        website: "WWW.MONTANHALAB.COM.BR",
        methodsUsed: ["KETTLEBELLS", "STEEL MACES", "CLUBBELLS", "CALISTHENICS", "MOBILITY LAB"],
        specialties: ["Força Não-Convencional", "Condicionamento Tático", "Prevenção de Lesões"],
        galleryPhotos: [
          "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=600&q=80",
          "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80",
          "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80",
        ],
        overviewText: "Projetado como um santuário para o treinamento de força pura, o Montanha Lab elimina o supérfluo para focar no que realmente constrói atletas resilientes: ferro maciço, alavancas assimétricas e protocolos de intensidade implacável.",
        missionText: "Nossa missão é transformar cada praticante em uma máquina de adaptação motora. Não ensinamos apenas movimentos; cultivamos a mentalidade espartana de execução sem desculpas em cada repetição.",
        philosophyText: "Sem máquinas guiadas. Sem esteiras anestésicas. Apenas você, a gravidade e o ferro.",
        anchoredQuote: "O ambiente certo não apenas inspira o esforço; ele torna a mediocridade insuportável.",
      },
      tags: ["Studio", "Spotlight", "Lab", "Academia"],
      estimatedReadTime: 3,
      featuredOnCover: false,
      enabled: true,
    },
  ],
  contentRepository: [
    {
      id: "doc-1",
      title: "O Segredo da Respiração Diafragmática e Pressão Intra-Abdominal (IAP)",
      rawContent: `A respiração no levantamento de peso pesado não é apenas para oxigenar o sangue; ela é uma ferramenta mecânica de estabilização da coluna. Quando realizamos a manobra de Valsalva controlada e expandimos o abdômen em 360 graus contra o cinto de musculação, criamos uma câmara hidráulica interna impenetrável.

Muitos atletas novatos cometem o erro fatal de encolher a barriga durante o agachamento ou levantamento terra. Isso transfere toda a carga cisalhante para as vértebras lombares. A forma correta é inflar a caixa abdominal como um cilindro de alta pressão.

O treinamento respiratório com kettlebells pesados ensina o corpo a manter essa rigidez enquanto se move. É o que chamamos de 'respiração por trás do escudo'. Você aprende a emitir força explosiva expirando com um chiado curto ('tsss!') no ápice do movimento, preservando a tensão no core.

Dominar essa técnica reduz o risco de hérnias de disco a quase zero e adiciona de 10% a 20% de carga imediata na sua barra. Treine a respiração diafragmática todos os dias antes de tocar no primeiro peso.`,
      category: "BIOMECÂNICA",
      sourceFileName: "respiracao-diafragmatica-iap.txt",
      wordCount: 168,
      status: "ready",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "doc-2",
      title: "Manual Completo do Remo Nórdico & Bioenergética: O Guia de Alta Densidade",
      rawContent: `O remo indoor e as variações nórdicas de tração representam um dos estímulos fisiológicos mais completos do planeta. Ao contrário da corrida onde o impacto articular é elevado, o remo oferece uma cadeia cinética fechada onde pernas, tronco e membros superiores trabalham em sinergia contínua de alta potência.

**A Fisiologia do Deslocamento de Potência**
Cada remada exige uma fase de impulsão balística liderada pelos quadríceps e glúteos (60% da força), seguida pela extensão controlada do quadril (20%) e finalizada pela tração dorsal com os braços (20%). Essa divisão garante que grandes grupos musculares dissipem a fadiga enquanto o coração é forçado a bombear sangue para todo o organismo simultaneamente.

**O Protocolo Nórdico de 500 Metros**
Para desenvolver um motor cardiovascular inabalável, o teste de 500m all-out é a referência padrão. Atletas de elite completam essa distância em menos de 1 minuto e 20 segundos. O acúmulo de lactato no sangue atinge níveis comparáveis aos de um combate profissional de MMA.

A recuperação entre tiros deve ser rigorosamente calculada com base na variabilidade da frequência cardíaca (HRV). Integrar o remo nórdico duas vezes por semana na sua periodização melhora a densidade mitocondrial, a capilarização muscular e a capacidade de suportar dor psicológica sob esforço máximo.

A consistência na cadência — mantendo entre 28 e 32 golpes por minuto com força máxima por braçada — separa os remadores comuns dos verdadeiros monstros da resistência muscular. O ferro forja o músculo, mas o ergômetro forja o coração do guerreiro.`,
      category: "CONDICIONAMENTO",
      sourceFileName: "guia-remo-nordico-completo.md",
      wordCount: 242,
      status: "draft",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  backCoverConfig: {
    headline: "FORJA O SEU CORPO. DOMINA A SUA MENTE.",
    subheadline: "Junte-se à fraternidade do Coach Montanha e treine com métodos não-convencionais de elite.",
    message: "A mediocridade é uma escolha, a excelência é uma disciplina diária. Pegue o peso, calce o tênis e vá para a arena.",
    backgroundImage: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1600&q=85",
    ctaText: "ACESSE O PROTOCOLO UNCONVENTIONAL",
    websiteUrl: "www.coachmontanha.com.br",
    socialHandles: {
      instagram: "@coachmontanha",
      youtube: "Coach Montanha Oficial",
      email: "contato@coachmontanha.com.br",
    },
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
