/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoostRouteImport } from './routes/boost'
import { Route as CreateRouteImport } from './routes/create'
import { Route as EcoRouteImport } from './routes/eco'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterAdminRouteImport } from './routes/master-admin'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as ApiProjectRouteImport } from './routes/api/project'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostRoute = BoostRouteImport.update({
  id: '/boost',
  path: '/boost',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EcoRoute = EcoRouteImport.update({
  id: '/eco',
  path: '/eco',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterAdminRoute = MasterAdminRouteImport.update({
  id: '/master-admin',
  path: '/master-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectRoute = ApiProjectRouteImport.update({
  id: '/api/project',
  path: '/api/project',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/boost': typeof BoostRoute
  '/create': typeof CreateRoute
  '/eco': typeof EcoRoute
  '/login': typeof LoginRoute
  '/master-admin': typeof MasterAdminRoute
  '/api/ai': typeof ApiAiRoute
  '/api/project': typeof ApiProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/boost': typeof BoostRoute
  '/create': typeof CreateRoute
  '/eco': typeof EcoRoute
  '/login': typeof LoginRoute
  '/master-admin': typeof MasterAdminRoute
  '/api/ai': typeof ApiAiRoute
  '/api/project': typeof ApiProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/boost': typeof BoostRoute
  '/create': typeof CreateRoute
  '/eco': typeof EcoRoute
  '/login': typeof LoginRoute
  '/master-admin': typeof MasterAdminRoute
  '/api/ai': typeof ApiAiRoute
  '/api/project': typeof ApiProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/boost'
    | '/create'
    | '/eco'
    | '/login'
    | '/master-admin'
    | '/api/ai'
    | '/api/project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/boost'
    | '/create'
    | '/eco'
    | '/login'
    | '/master-admin'
    | '/api/ai'
    | '/api/project'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/boost'
    | '/create'
    | '/eco'
    | '/login'
    | '/master-admin'
    | '/api/ai'
    | '/api/project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BoostRoute: typeof BoostRoute
  CreateRoute: typeof CreateRoute
  EcoRoute: typeof EcoRoute
  LoginRoute: typeof LoginRoute
  MasterAdminRoute: typeof MasterAdminRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiProjectRoute: typeof ApiProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boost': {
      id: '/boost'
      path: '/boost'
      fullPath: '/boost'
      preLoaderRoute: typeof BoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eco': {
      id: '/eco'
      path: '/eco'
      fullPath: '/eco'
      preLoaderRoute: typeof EcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-admin': {
      id: '/master-admin'
      path: '/master-admin'
      fullPath: '/master-admin'
      preLoaderRoute: typeof MasterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project': {
      id: '/api/project'
      path: '/api/project'
      fullPath: '/api/project'
      preLoaderRoute: typeof ApiProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BoostRoute: BoostRoute,
  CreateRoute: CreateRoute,
  EcoRoute: EcoRoute,
  LoginRoute: LoginRoute,
  MasterAdminRoute: MasterAdminRoute,
  ApiAiRoute: ApiAiRoute,
  ApiProjectRoute: ApiProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
